# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloadingui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow

class Ui_Form(QMainWindow):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setObjectName("Form")
        self.resize(400, 300)
        self.setupUi()
    def setupUi(self):
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_info = QtWidgets.QLabel(self)
        self.title_info.setObjectName("title_info")
        self.verticalLayout.addWidget(self.title_info)
        self.progressBar = QtWidgets.QProgressBar(self)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.install_info = QtWidgets.QPlainTextEdit(self)
        self.install_info.setObjectName("install_info")
        self.verticalLayout.addWidget(self.install_info)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "安装中..."))
        self.title_info.setText(_translate("Form", "正在安装，请稍后..."))

if __name__ == '__main__':
    app = QApplication([])
    window = Ui_Form()
    window.show()
    sys.exit(app.exec())